### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by projjalm** [Abizer-R/QuickEdit-Photo-Editor#27]

**Comment by licaon-kter** [comment]
Ref: https://f-droid.org/docs/Inclusion_Policy/

**Comment by xxxxme** [comment]
For now, it's available from IzzyOnDroid which is sufficient for me.

**Comment by licaon-kter** [comment]
But are you against it's inclusion?

**Comment by Cwpute** [comment]
Fdroid is a store on which a lot more diverse people come and browse apps, whereas IzzyOnDroid is definitely more directed towards developers and tech enthusiasts.
Getting your app listed directly on Fdroid would allow it to reach a lot more potential users !

**Comment by licaon-kter** [comment]
https://github.com/Abizer-R/QuickEdit-Photo-Editor/pull/31

**Comment by licaon-kter** [comment]
this recipe **metadata/com.abizer_r.quickedit.yml**
```
Categories:
  - Graphics
License: Apache-2.0
SourceCode: https://github.com/Abizer-R/QuickEdit-Photo-Editor
IssueTracker: https://github.com/Abizer-R/QuickEdit-Photo-Editor/issues

AutoName: QuickEdit

RepoType: git
Repo: https://github.com/Abizer-R/QuickEdit-Photo-Editor.git
Binaries: https://github.com/Abizer-R/QuickEdit-Photo-Editor/releases/download/v%v-%c/app-release.apk

Builds:
  - versionName: 1.1.0
    versionCode: 4
    commit: 9ffbe535550a907f54f63b3b6ec6e988a25c354d
    subdir: app
    gradle:
      - yes
    srclibs:
      - reproducible-apk-tools@v0.3.0
    postbuild: $$reproducible-apk-tools$$/inplace-fix.py --zipalign --page-align fix-newlines
      $$OUT$$ 'META-INF/services/*'

AllowedAPKSigningKeys: 774726bbbcc5ed40bb476af8f94290e019b5eb8262954957cde9c2d8d162df19

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 1.1.0
CurrentVersionCode: 4
```

builds fine and is build reproducible (ref: https://f-droid.org/docs/Inclusion_How-To/#reproducible-builds) :tada: 

once you merge my PRs above and release a new version, the app can be included @xxxxme
